accelerator: gpu
devices: 1

dataset_root: /nydl/data/Stanford_Online_Products/
dataframe_name: df.csv

logs_root: /nydl/logs/Stanford_Online_Products/

bs_val: 512
num_workers: 20

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: True
    use_multi_scale: False
    weights: vits16_sop

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 5]
  map_top_k: [5]
  fmr_vals: [1]
  return_only_main_category: False
  visualize_only_main_category: True

log_images: False

hydra:
  searchpath:
   - pkg://oml.configs
