dataset_root: data/Stanford_Online_Products/
dataframe_name: df.csv

logs_root: logs/Stanford_Online_Products/

bs_val: 512
num_workers: 20

transforms_val: null

model:
  name: vit
  args:
    arch: vits16
    normalise_features: True
    use_multi_scale: False
    weights: vits16_sop

metric_args:
  cmc_top_k: [1, 5]
  map_top_k: [5]

log_only_main_category: False

gpus:
  - 0
  - 1

hydra:
  searchpath:
    - file://../../configs
