accelerator: gpu
devices: 1

dataset_root: data/CUB_200_2011/
dataframe_name: df.csv

logs_root: logs/CUB_200_2011/

bs_val: 256
num_workers: 8

transforms_val:
  name: norm_resize_albu
  args:
    im_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: False
    use_multi_scale: False
    weights: vits16_cub


metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 5]
  map_top_k: [5]
  fmr_vals: [0.5, 0.1, 0.01, 0.001]
  precision_top_k: [5]
  return_only_main_category: False
  visualize_only_main_category: True

log_images: False

hydra:
  searchpath:
   - pkg://oml.configs
