dataset_root: /nydl/data/DeepFashion_InShop/
dataframe_name: df.csv

logs_root: logs

im_size: 224
bs_val: 512
num_workers: 20


model:
  name: vit
  args:
    arch: vits8
    normalise_features: False
    use_multi_scale: False
    weights: pretrained_dino
    strict_load: True


gpus:
  - 0
  - 1

hydra:
  searchpath:
    - file://../../configs
