dataset_root: data/DeepFashion_InShop/
dataframe_name: df_fixed_val.csv

logs_root: logs/DeepFashion_InShop/

im_size: 224
bs_val: 512
num_workers: 20


model:
  name: vit
  args:
    arch: vits16
    normalise_features: False
    use_multi_scale: False
    weights: vits16_inshop


metric_args:
  cmc_top_k: [1, 5]
  map_top_k: [5]
  precision_top_k: [5]


log_only_main_category: False


hydra:
  searchpath:
    - file://../../configs
